// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function clicked() {
  console.log("clicked");
  return /* () */0;
}

var component = ReasonReact.statelessComponent("Beer");

function make(beer, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "row"
                    }, React.createElement("div", {
                          className: "col-md-12"
                        }, React.createElement("div", {
                              className: "tile center-block"
                            }, React.createElement("h3", {
                                  className: "tile-title"
                                }, beer[/* name */2]), React.createElement("br", undefined), React.createElement("a", {
                                  href: "",
                                  onClick: clicked
                                }, React.createElement("img", {
                                      className: "image",
                                      height: "300px",
                                      src: beer[/* bottleImageLink */8]
                                    })), React.createElement("div", undefined, React.createElement("br", undefined)), React.createElement("div", {
                                  dangerouslySetInnerHTML: {
                                    __html: beer[/* description */3]
                                  }
                                }), React.createElement("button", {
                                  className: "btn btn-secondary btn-large btn-block",
                                  onClick: clicked
                                }, "Detail"), React.createElement("button", {
                                  className: "btn btn-success btn-large btn-block",
                                  onClick: clicked
                                }, "Order")))));
    });
  return newrecord;
}

exports.clicked   = clicked;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
