// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Contact");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "section section-we-do-2",
                  id: "brewery"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: "row"
                        }, React.createElement("h2", undefined, "Our Mentality"), React.createElement("img", {
                              className: "img-rounded img-responsive",
                              src: "assets/img/beer/mentality.jpg"
                            })), React.createElement("div", {
                          className: "row"
                        }, React.createElement("br", undefined)), React.createElement("div", {
                          className: "row"
                        }, React.createElement("div", {
                              className: "col-md-4"
                            }, React.createElement("div", {
                                  className: "card"
                                }, React.createElement("div", {
                                      className: "icon"
                                    }, React.createElement("img", {
                                          className: "img-rounded img-responsive center-block",
                                          src: "assets/img/icons/png/ingredients.png"
                                        }), React.createElement("i", {
                                          className: "pe-7s-gift"
                                        })), React.createElement("h3", undefined, "Best Ingredients"), React.createElement("p", undefined, "According to craft beer brewing tradition we use only the best quality ingredients. We rely mostly on traditional ingredients like water, malt, hops and yeast but include a wide range of additional natural ingredients that produce unique and interesting tastes. We do not have our own brewery, but use the equipment of several midget- and micro-breweries in Austria and Slovakia."))), React.createElement("div", {
                              className: "col-md-4"
                            }, React.createElement("div", {
                                  className: "card"
                                }, React.createElement("div", {
                                      className: "icon"
                                    }, React.createElement("img", {
                                          className: "img-rounded img-responsive center-block",
                                          src: "assets/img/icons/png/brewing.png"
                                        }), React.createElement("i", {
                                          className: "pe-7s-rocket"
                                        })), React.createElement("h3", undefined, "High Quality"), React.createElement("p", undefined, "Quality is a must and throughout the entire production of our beer we make sure of high quality standards. Besides the wonderful and tasty spring water from the Austrian mountains we rely on premium quality malts from Austria, Slovakia, Czech Republic, Germany and the U.K. Traditional and \xe2\x80\x9cnew world\xe2\x80\x9d hops from around the world and most reliable and proven yeast strains available."))), React.createElement("div", {
                              className: "col-md-4"
                            }, React.createElement("div", {
                                  className: "card"
                                }, React.createElement("div", {
                                      className: "icon"
                                    }, React.createElement("img", {
                                          className: "img-rounded img-responsive center-block",
                                          src: "assets/img/icons/png/glass.png"
                                        }), React.createElement("i", {
                                          className: "pe-7s-tools"
                                        })), React.createElement("h3", undefined, "Creative Taste"), React.createElement("p", undefined, "Our beer styles are brewed using the best recipes we collected over years of brewing Craft beer. This way we can use the advantages of the respective equipment to maximize the aromatic profile of our beers. We believe it is not enough to produce a crisp and refreshing beer. We go a step further to bring you an interesting and delicate tasting, enjoyable, high-quality and sometimes challenging drinking experience."))))), React.createElement("div", {
                      className: "row"
                    }, React.createElement("img", {
                          className: "img-responsive center-block",
                          style: {
                            height: "100px"
                          },
                          src: "assets/img/beer/logo.png"
                        })));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
