// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Contact");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "section section-contact",
                  id: "contact"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: "title"
                        }, React.createElement("h2", undefined, "Contact us"), React.createElement("p", undefined, "6 beers brewering company"), React.createElement("p", undefined, "Margaritenweg 23, 2384 Breitenfurt"), React.createElement("p", undefined, "Austria"), React.createElement("p", undefined, "Tel.: +43 677 624 168 66"), React.createElement("button", {
                              className: "btn btn-success btn-large"
                            }, "Email")), React.createElement("div", {
                          className: "row"
                        }, React.createElement("div", {
                              className: "col-md-12 center-block",
                              id: "map-container",
                              style: {
                                height: "300px",
                                filter: "grayscale(100%)"
                              }
                            })), React.createElement("br", undefined), React.createElement("img", {
                          className: "img-responsive center-block",
                          style: {
                            height: "100px"
                          },
                          src: "assets/img/beer/logo.png"
                        })));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
