// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Footer");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("footer", {
                  className: "footer footer-color-black"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("nav", {
                          className: "pull-left"
                        }, React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                                      href: "#"
                                    }, "Home")), React.createElement("li", undefined, React.createElement("a", {
                                      href: "terms.html",
                                      target: "_blank"
                                    }, "Terms & Conditions")))), React.createElement("div", {
                          className: "social-area pull-right"
                        }, React.createElement("a", {
                              className: "btn btn-social btn-facebook btn-simple",
                              href: "https://www.facebook.com/6beersbrewing"
                            }, React.createElement("span", {
                                  className: "fui-facebook"
                                })), React.createElement("a", {
                              className: "btn btn-social btn-instagram btn-simple",
                              href: "https://instagram.com/6beersbrewing"
                            }, React.createElement("span", {
                                  className: "fui-instagram"
                                }))), React.createElement("div", {
                          className: "copyright"
                        }, "Copyright 2017 ", React.createElement("a", {
                              href: "http://www.6beers.at",
                              target: "_blank"
                            }, "6 beers brewing co."))));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
