// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("nav", {
                  className: "navbar navbar-inverse navbar-fixed-top",
                  role: "navigation"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: "navbar-header"
                        }, React.createElement("button", {
                              className: "navbar-toggle",
                              id: "menu-toggle"
                            }), React.createElement("a", {
                              className: "navbar-brand",
                              href: "#"
                            }, "6 beers brewing co.")), React.createElement("div", {
                          className: "collapse navbar-collapse"
                        }, React.createElement("ul", {
                              className: "nav navbar-nav navbar-right navbar-uppercase"
                            }, React.createElement("li", {
                                  className: "social-links"
                                }, React.createElement("a", {
                                      href: "https://www.facebook.com/6beersbrewing"
                                    }, React.createElement("span", {
                                          className: "fui-facebook"
                                        })), React.createElement("a", {
                                      href: "https://instagram.com/6beersbrewing"
                                    }, React.createElement("span", {
                                          className: "fui-instagram"
                                        }))), React.createElement("li", undefined, React.createElement("a", {
                                      href: "#/brewery"
                                    }, "Brewery")), React.createElement("li", undefined, React.createElement("a", {
                                      href: "#/beer"
                                    }, "Beer")), React.createElement("li", undefined, React.createElement("a", {
                                      href: "#/order"
                                    }, "Make an Order")), React.createElement("li", undefined, React.createElement("a", {
                                      href: "#/contact"
                                    }, "Contact Us"))))));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
