// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Header      = require("./components/header.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function click(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

var component = ReasonReact.statelessComponent("App");

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "App"
                }, ReasonReact.element(/* None */0, /* None */0, Header.make(/* array */[])), React.createElement("div", {
                      className: "footer"
                    }));
    });
  return newrecord;
}

exports.click     = click;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
